
SHORT_FORM = {
    'afaik': 'As Far As I Know',
     'afk': 'Away From Keyboard',
     'asap': 'As Soon As Possible',
     'atk': 'At The Keyboard',
     'atm': 'At The Moment',
     'a3': 'Anytime, Anywhere, Anyplace',
     'bak': 'Back At Keyboard',
     'bbl': 'Be Back Later',
     'bbs': 'Be Back Soon',
     'bfn': 'Bye For Now',
     'b4n': 'Bye For Now',
     'brb': 'Be Right Back',
     'brt': 'Be Right There',
     'btw': 'By The Way',
     'b4': 'Before',
     'cu': 'See You',
     'cul8r': 'See You Later',
     'cya': 'See You',
     'faq': 'Frequently Asked Questions',
     'fc': 'Fingers Crossed',
     'fwiw': "For What It's Worth",
     'fyi': 'For Your Information',
     'gal': 'Get A Life',
     'gg': 'Good Game',
     'gn': 'Good Night',
     'gmta': 'Great Minds Think Alike',
     'gr8': 'Great!',
     'g9': 'Genius',
     'ic': 'I See',
     'icq': 'I Seek you (also a chat program)',
     'ilu': 'ILU: I Love You',
     'imho': 'In My Honest/Humble Opinion',
     'imo': 'In My Opinion',
     'iow': 'In Other Words',
     'irl': 'In Real Life',
     'kiss': 'Keep It Simple, Stupid',
     'ldr': 'Long Distance Relationship',
     'lmao': 'Laugh My A.. Off',
     'lol': 'Laughing Out Loud',
     'ltns': 'Long Time No See',
     'l8r': 'Later',
     'mte': 'My Thoughts Exactly',
     'm8': 'Mate',
     'nrn': 'No Reply Necessary',
     'oic': 'Oh I See',
     'pita': 'Pain In The A..',
     'prt': 'Party',
     'prw': 'Parents Are Watching',
     'rofl': 'Rolling On The Floor Laughing',
     'roflol': 'Rolling On The Floor Laughing Out Loud',
     'rotflmao': 'Rolling On The Floor Laughing My A.. Off',
     'sk8': 'Skate',
     'stats': 'Your sex and age',
     'asl': 'Age, Sex, Location',
     'thx': 'Thank You',
     'ttfn': 'Ta-Ta For Now!',
     'ttyl': 'Talk To You Later',
     'u': 'You',
     'u2': 'You Too',
     'u4e': 'Yours For Ever',
     'wb': 'Welcome Back',
     'wtf': 'What The F...',
     'wtg': 'Way To Go!',
     'wuf': 'Where Are You From?',
     'w8': 'Wait...',
     '7k': 'Sick:-D Laugher',
     'fwb': 'friend with benefit',
     '69': 'sex',
     'wdym': 'What do you mean',
     'wby': 'What about you',
     'omg': 'Oh my god',
    "ain't": "are not",
    "aren't": "are not",
    "can't": "cannot",
    "can't've": "cannot have",
    "'cause": "because",
    "could've": "could have",
    "couldn't": "could not",
    "couldn't've": "could not have",
    "didn't": "did not",
    "doesn't": "does not",
    "don't": "do not",
    "hadn't": "had not",
    "hadn't've": "had not have",
    "hasn't": "has not",
    "haven't": "have not",
    "he'd": "he would",
    "he'd've": "he would have",
    "he'll": "he will",
    "he'll've": "he will have",
    "he's": "he is",
    "how'd": "how did",
    "how'd'y": "how do you",
    "how'll": "how will",
    "how's": "how is",
    "i'd": "I had",
    "i'd've": "I would have",
    "i'll": "I will",
    "i'll've": "I will have",
    "i'm": "I am",
    "i've": "I have",
    "isn't": "is not",
    "it'd": "it would",
    "it'd've": "it would have",
    "it'll": "it will",
    "it'll've": "it will have",
    "it's": "it is",
    "let's": "let us",
    "ma'am": "madam",
    "mayn't": "may not",
    "might've": "might have",
    "mightn't": "might not",
    "mightn't've": "might not have",
    "must've": "must have",
    "mustn't": "must not",
    "mustn't've": "must not have",
    "needn't": "need not",
    "needn't've": "need not have",
    "o'clock": "of the clock",
    "oughtn't": "ought not",
    "oughtn't've": "ought not have",
    "shan't": "shall not",
    "sha'n't": "shall not",
    "shan't've": "shall not have",
    "she'd": "she would",
    "she'd've": "she would have",
    "she'll": "she will",
    "she'll've": "she will have",
    "she's": "she is",
    "should've": "should have",
    "shouldn't": "should not",
    "shouldn't've": "should not have",
    "so've": "so have",
    "so's": "so is",
    "that'd": "that had",
    "that'd've": "that would have",
    "that's": "that is",
    "there'd": "there would",
    "there'd've": "there would have",
    "there's": "there is",
    "they'd": "they would",
    "they'd've": "they would have",
    "they'll": "they will",
    "they'll've": "they will have",
    "they're": "they are",
    "they've": "they have",
    "to've": "to have",
    "wasn't": "was not",
    "we'd": "we would",
    "we'd've": "we would have",
    "we'll": "we will",
    "we'll've": "we will have",
    "we're": "we are",
    "we've": "we have",
    "weren't": "were not",
    "what'll": "what will",
    "what'll've": "what will have",
    "what're": "what are",
    "what's": "what is",
    "what've": "what have",
    "when's": "when is",
    "when've": "when have",
    "where'd": "where did",
    "where's": "where is",
    "where've": "where have",
    "who'll": "who will",
    "who'll've": "who will have",
    "who's": "wwho is",
    "who've": "who have",
    "why's": "why is",
    "why've": "why have",
    "will've": "will have",
    "won't": "will not",
    "won't've": "will not have",
    "would've": "would have",
    "wouldn't": "would not",
    "wouldn't've": "would not have",
    "y'all": "you all",
    "y'all'd": "you all would",
    "y'all'd've": "you all would have",
    "y'all're": "you all are",
    "y'all've": "you all have",
    "you'd": "you would",
    "you'd've": "you would have",
    "you'll": "you will",
    "you'll've": "you will have",
    "you're": "you are",
    "you've": "you have"
}